### PR TITLE
Brings esp32 branch up to date with current master

### PR DESCRIPTION
**Pull request by AngryMikey**
This change brings the code up to date against the current master branch.

It also changes platformio.ini to be able to build esp8266, esp8266 with wifi, and esp32.

Esp32 with Wifi is able to talk with Fermentrack, although Fermentrack thinks it is an 8266 board.

### CODE REVIEW

**Comment by daveconde** [comment]
I just flashed this to an ESP32 and it seems to work really well. It would be awesome to get this merged along with adding in the tilt bridge support so it all worked from a single device.

**Comment by thorrak** [comment]
I’d love to, but it can’t (easily) happen. TiltBridge uses 99.6% of available flash with most widely available ESP32 boards, thanks to the size of the Bluetooth stack.

I have an ESP32 test build at home, but don’t want to officially release it/post about it until it has rotary encoder support. That was the only feature missing from the ESP8266 build, and with the ESP32 we’ve got the pins. Unfortunately, I’ve had a few (good!) things come up recently which has dramatically curtailed my ability to work on this/Fermentrack/brewing. Hoping to have those sorted either by this coming weekend or next week, though!

Sent from my iPhone

On May 29, 2019, at 4:56 PM, David Conde <notifications@github.com<mailto:notifications@github.com>> wrote:


I just flashed this to an ESP32 and it seems to work really well. It would be awesome to get this merged along with adding in the tilt bridge support so it all worked from a single device.

**Comment by daveconde** [comment]
No worries, I’ve been using the tilt support on the pi with fermentrack so having it on the ESP32 is more of a nice to have. Looking forward to the official ESP32 release 👍

**Comment by AngryMikey** [comment]
Things I think need to be done before releasing this:

1) Adding support to Fermentrack and the ESP32 firmware to differentiate between the two.  Currently it broadcasts that it is an 8266. I don't think flashing an esp32 with esp8266 code is going to work, but still they should be different in that code.
2) I did a quick hack to just generate the AP station name by copying around.  Should we separate that into an ESP class?
3) Figure out if it is normal that it still broadcasts as an AP when connected to a Wifi network.  I don't think that behavior is correct.
4) Make sure ESP8266s still work properly with this code.  

 Is rotary support to allow accessing menus from the LCD?

**Comment by thorrak** [comment]
#1: That’s odd - when I did the ESP32 port, I thought I changed the code to detect/broadcast as a different chipset. That should be an easy fix, I’ll take a look.

#2: Same... I changed the code to detect if it was an ESP32 and do *something* different to come up with an AP name. That said, the entire WiFi functionality needs to be refactored to take into account lessons learned from TiltBridge.

#3: This is absolutely not normal. TiltBridge doesn’t do it, so refactoring would help I think.

#4: It did with my port - need to check the pull request. You’ll have to flash a different firmware obviously but both compiled, and both of the ones that compiled worked.

Correct - it reenables “menu” support on the device to allow control from the LCD.

Sent from my iPhone

On May 30, 2019, at 9:43 PM, AngryMikey <notifications@github.com<mailto:notifications@github.com>> wrote:


Things I think need to be done before releasing this:

  1.  Adding support to Fermentrack and the ESP32 firmware to differentiate between the two. Currently it broadcasts that it is an 8266. I don't think flashing an esp32 with esp8266 code is going to work, but still they should be different in that code.
  2.  I did a quick hack to just generate the AP station name by copying around. Should we separate that into an ESP class?
  3.  Figure out if it is normal that it still broadcasts as an AP when connected to a Wifi network. I don't think that behavior is correct.
  4.  Make sure ESP8266s still work properly with this code.

Is rotary support to allow accessing menus from the LCD?

**Comment by AngryMikey** [comment]
Regarding 1, the place I saw the BrewPi8266 was in the wifi MDNS settings.

Should I change that to be dependent on the board version?

Starting at brewpi-esp8266.cpp:215

#ifdef ESP8266_WiFi
	// If we're using WiFi, initialize the bridge
	server.begin();
	server.setNoDelay(true);
	// mDNS will stop responding after awhile unless we query the specific service we want
	MDNS.addService("brewpi", "tcp", 23);
	MDNS.addServiceTxt("brewpi", "tcp", "board", "ESP8266");
	MDNS.addServiceTxt("brewpi", "tcp", "branch", "legacy");
	MDNS.addServiceTxt("brewpi", "tcp", "version", VERSION_STRING);
	MDNS.addServiceTxt("brewpi", "tcp", "revision", FIRMWARE_REVISION);
#endif

I'm guessing I should add a #ifdef there to set it to ESP32 or ESP8266

**Comment by thorrak** [comment]
I recently started to get the ESP32 support finalized, and ended up making these changes separate to this pull request. Going to close this one for now. 

That said, for anyone following this who is interested in ESP32 support - I should have it available by the end of the year - along with support for TFT displays.

**Pull request closed without merging**
